from app.api.routes import health
from app.api.routes import orders
from app.api.routes import shipments
from app.api.routes import after_sales
from app.api.routes import conversations
from app.api.routes import context
from app.api.routes import customers
from app.api.routes import kb
from app.api.routes import management
from app.api.routes import recommendations
from app.api.routes import quality
from app.api.routes import risk
from app.api.routes import integration
from app.api.routes import analytics
from app.api.routes import operations
from app.api.routes import risk_flags
from app.api.routes import audit_logs
from app.api.routes import followup_tasks
from app.api.routes import push_events
from app.api.routes import ai_suggestion
