[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin
csv_internal_sep = ,
db_maxconn = 64
db_name = False
db_template = template1
db_user = odoo
db_password = odoo
db_host = db
db_port = 5432
db_sslmode = prefer
db_timeout = 60
db_max_size = 100
db_maxconn_gevent = 10
list_db = True
http_enable = True
http_interface = 
http_port = 8069
longpolling_port = 8072
proxy_mode = False
workers = 0
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = 120
logfile = /var/log/odoo/odoo-server.log
logrotate = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
log_web = True
log_sql = False
syslog = False
syslog_facility = LOG_USER
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
server_wide_modules = base,web
max_cron_threads = 2
unaccent = False
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
transient_age_limit = 1.0
transient_count_limit = False
test_enable = False
test_file = False
test_tags = None
test_commit = False
test_report_directory = False
